### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by ultrasaurus** [oaktown/calliope#52]
tried downloading all emails again, and getting this error (after it got stuck a couple of times)

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1444363]

goroutine 1 [running]:
github.com/oaktown/calliope/gmailservice.DownloadLabels(0xc42002e060, 0xc42002e0c0, 0x0, 0xc42021c000, 0xc8, 0xc42017a300, 0x7ffeefbff6c9, 0x11, 0x7a120, 0x16ef880, ...)
	/Users/sarahallen/go/src/github.com/oaktown/calliope/gmailservice/gmailservice.go:70 +0xd3
github.com/oaktown/calliope/gmailservice.Download(0xc42002e060, 0xc42002e0c0, 0x0, 0xc42021c000, 0xc8, 0xc42017a300, 0x7ffeefbff6c9, 0x11, 0x7a120, 0x16ef880, ...)
	/Users/sarahallen/go/src/github.com/oaktown/calliope/gmailservice/gmailservice.go:60 +0x52
github.com/oaktown/calliope/cmd.download()
	/Users/sarahallen/go/src/github.com/oaktown/calliope/cmd/download.go:84 +0x46a

**Comment by ultrasaurus** [comment]
tried on gmail-retry branch, using command `./calliope download -l 500000`
 got a similar error, earlier this time, after 8311 emails (Earliest email date: 2018-09-06), 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1446709]

goroutine 150990 [running]:
github.com/oaktown/calliope/gmailservice.(*Downloader).tryThrice(0xc420e82630, 0xc4207d43f0, 0xc42001e600, 0xc42009d501)
	/Users/sarahallen/go/src/github.com/oaktown/calliope/gmailservice/gmailservice.go:290 +0x59
github.com/oaktown/calliope/gmailservice.(*Downloader).DoGetWrapper(0xc420e82630, 0xc4215df340, 0x10, 0x0, 0xc4203024e0, 0x1)
	/Users/sarahallen/go/src/github.com/oaktown/calliope/gmailservice/gmailservice.go:213 +0xb0
github.com/oaktown/calliope/gmailservice.DownloadFullMessage(0xc420182240, 0xc4201822a0, 0x0, 0xc42023e000, 0xc8, 0xc42015e300, 0x0, 0x0, 0x7a120, 0x16f0868, ...)
	/Users/sarahallen/go/src/github.com/oaktown/calliope/gmailservice/gmailservice.go:180 +0xd7
created by github.com/oaktown/calliope/gmailservice.DownloadFullMessages
	/Users/sarahallen/go/src/github.com/oaktown/calliope/gmailservice/gmailservice.go:143 +0x11b

**Comment by ultrasaurus** [comment]
I printed out more detail, we're definitely getting a `googleapi.Error`

```
:05:54 ====> error type: *googleapi.Error
2018/12/30 09:05:54 ====> error: googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/gmail.googleapis.com/quotas?project=758132511498, userRateLimitExceeded

2018/12/30 09:05:54 err.(*googleapi.Error).Code googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/gmail.googleapis.com/quotas?project=758132511498, userRateLimitExceeded
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1446710]

goroutine 102263 [running]:
github.com/oaktown/calliope/gmailservice.(*Downloader).tryThrice(0xc421158630, 0xc420188780, 0xc42020d600, 0xc420523201)
	/Users/sarahallen/go/src/github.com/oaktown/calliope/gmailservice/gmailservice.go:299 +0x60
github.com/oaktown/calliope/gmailservice.(*Downloader).DoGetWrapper(0xc421158630, 0xc42047d8e0, 0x10, 0x0, 0xc4200af8b8, 0x1)
	/Users/sarahallen/go/src/github.com/oaktown/calliope/gmailservice/gmailservice.go:213 +0xb0
github.com/oaktown/calliope/gmailservice.DownloadFullMessage(0xc42002e1e0, 0xc42002e240, 0x0, 0xc420290000, 0xc8, 0xc420188300, 0x0, 0x0, 0xf4240, 0x16f0afe, ...)
```
